[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["12295"]
edition = "2018"

[profile.dev]
opt-level = 2

[dependencies]
num-traits = "0.2"
rand = "0.7"
image = "0.23"
indicatif = "0.14"
num_cpus = "1.10"