name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run
      run: cargo run --release -- -c NextWeekFinalScene -p 3
    - name: Upload output image
      uses: actions/upload-artifact@v2
      with:
        name: out.png
        path: 'out.png'
